export const SAVE_TOKEN = "AUTH/SAVE_TOKEN";
export const DELETE_TOKEN = "AUTH/DELETE_TOKEN";

export const SAVE_CURRENT_USER = "AUTH/SAVE_CURRENT_USER";
export const DELETE_CURRENT_USER = "AUTH/DELETE_CURRENT_USER";
